"""payment_operations_tables

Revision ID: 937904a33105
Revises: a1b42d971924
Create Date: 2026-08-09 10:12:20.465859+00:00
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

import app.db.base  # noqa: F401 - UTCDateTime is referenced by the column definitions

revision: str = '937904a33105'
down_revision: Union[str, None] = 'a1b42d971924'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('payment_instructions',
    sa.Column('payment_reference', sa.String(length=35), nullable=False),
    sa.Column('uetr', sa.String(length=36), nullable=False),
    sa.Column('end_to_end_id', sa.String(length=35), nullable=False),
    sa.Column('message_type', sa.String(length=16), nullable=False),
    sa.Column('direction', sa.String(length=12), nullable=False),
    sa.Column('rail', sa.String(length=16), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('debtor_name', sa.String(length=160), nullable=False),
    sa.Column('debtor_account', sa.String(length=34), nullable=False),
    sa.Column('debtor_agent_bic', sa.String(length=11), nullable=False),
    sa.Column('creditor_name', sa.String(length=160), nullable=False),
    sa.Column('creditor_account', sa.String(length=34), nullable=False),
    sa.Column('creditor_agent_bic', sa.String(length=11), nullable=False),
    sa.Column('intermediary_bic', sa.String(length=11), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('charge_bearer', sa.String(length=8), nullable=False),
    sa.Column('charges_deducted', sa.Float(), nullable=False),
    sa.Column('remittance_info', sa.String(length=280), nullable=False),
    sa.Column('purpose_code', sa.String(length=8), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('status_reason', sa.String(length=140), nullable=True),
    sa.Column('screening_status', sa.String(length=16), nullable=False),
    sa.Column('submitted_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('value_date', sa.Date(), nullable=True),
    sa.Column('settled_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('cutoff_missed', sa.Boolean(), nullable=False),
    sa.Column('duplicate_of', sa.String(length=36), nullable=True),
    sa.Column('attributes', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_instructions', schema=None) as batch_op:
        batch_op.create_index('ix_payment_customer', ['customer_id', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_instructions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_instructions_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_instructions_direction'), ['direction'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_instructions_payment_reference'), ['payment_reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_payment_instructions_screening_status'), ['screening_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_instructions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_instructions_uetr'), ['uetr'], unique=True)
        batch_op.create_index(batch_op.f('ix_payment_instructions_value_date'), ['value_date'], unique=False)
        batch_op.create_index('ix_payment_status_value', ['status', 'value_date'], unique=False)

    op.create_table('payment_investigations',
    sa.Column('case_number', sa.String(length=32), nullable=False),
    sa.Column('payment_id', sa.String(length=36), nullable=False),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('raised_by', sa.String(length=24), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('resolution', sa.String(length=48), nullable=True),
    sa.Column('resolution_note', sa.Text(), nullable=True),
    sa.Column('tat_deadline', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('compensation_due', sa.Float(), nullable=False),
    sa.Column('compensation_paid', sa.Float(), nullable=False),
    sa.Column('opened_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('closed_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('execution_id', sa.String(length=36), nullable=True),
    sa.Column('attributes', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payment_instructions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_investigations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_investigations_case_number'), ['case_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_payment_investigations_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_investigations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_investigations_execution_id'), ['execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_investigations_opened_at'), ['opened_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_investigations_payment_id'), ['payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_investigations_status'), ['status'], unique=False)

    op.create_table('payment_repairs',
    sa.Column('payment_id', sa.String(length=36), nullable=False),
    sa.Column('field_name', sa.String(length=40), nullable=False),
    sa.Column('previous_value', sa.String(length=280), nullable=False),
    sa.Column('repaired_value', sa.String(length=280), nullable=False),
    sa.Column('reason', sa.String(length=140), nullable=False),
    sa.Column('repair_type', sa.String(length=24), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_by', sa.String(length=160), nullable=True),
    sa.Column('execution_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payment_instructions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_repairs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_repairs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_repairs_execution_id'), ['execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_repairs_payment_id'), ['payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_repairs_status'), ['status'], unique=False)

    op.create_table('payment_returns',
    sa.Column('return_reference', sa.String(length=35), nullable=False),
    sa.Column('payment_id', sa.String(length=36), nullable=False),
    sa.Column('reason_code', sa.String(length=8), nullable=False),
    sa.Column('reason_description', sa.String(length=160), nullable=False),
    sa.Column('message_type', sa.String(length=16), nullable=False),
    sa.Column('returned_amount', sa.Float(), nullable=False),
    sa.Column('charges_retained', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('approved_by', sa.String(length=160), nullable=True),
    sa.Column('issued_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('execution_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payment_instructions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_returns', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_returns_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_returns_execution_id'), ['execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_returns_payment_id'), ['payment_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_returns_reason_code'), ['reason_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_returns_return_reference'), ['return_reference'], unique=True)
        batch_op.create_index(batch_op.f('ix_payment_returns_status'), ['status'], unique=False)

    op.create_table('payment_screening_hits',
    sa.Column('payment_id', sa.String(length=36), nullable=False),
    sa.Column('matched_field', sa.String(length=24), nullable=False),
    sa.Column('matched_value', sa.String(length=200), nullable=False),
    sa.Column('list_name', sa.String(length=48), nullable=False),
    sa.Column('list_entry_id', sa.String(length=64), nullable=True),
    sa.Column('match_score', sa.Float(), nullable=False),
    sa.Column('disposition', sa.String(length=20), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('decided_by', sa.String(length=160), nullable=True),
    sa.Column('decided_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('execution_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['payment_id'], ['payment_instructions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('payment_screening_hits', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_payment_screening_hits_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_screening_hits_disposition'), ['disposition'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_screening_hits_execution_id'), ['execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_payment_screening_hits_payment_id'), ['payment_id'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('payment_screening_hits', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_screening_hits_payment_id'))
        batch_op.drop_index(batch_op.f('ix_payment_screening_hits_execution_id'))
        batch_op.drop_index(batch_op.f('ix_payment_screening_hits_disposition'))
        batch_op.drop_index(batch_op.f('ix_payment_screening_hits_created_at'))

    op.drop_table('payment_screening_hits')
    with op.batch_alter_table('payment_returns', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_returns_status'))
        batch_op.drop_index(batch_op.f('ix_payment_returns_return_reference'))
        batch_op.drop_index(batch_op.f('ix_payment_returns_reason_code'))
        batch_op.drop_index(batch_op.f('ix_payment_returns_payment_id'))
        batch_op.drop_index(batch_op.f('ix_payment_returns_execution_id'))
        batch_op.drop_index(batch_op.f('ix_payment_returns_created_at'))

    op.drop_table('payment_returns')
    with op.batch_alter_table('payment_repairs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_repairs_status'))
        batch_op.drop_index(batch_op.f('ix_payment_repairs_payment_id'))
        batch_op.drop_index(batch_op.f('ix_payment_repairs_execution_id'))
        batch_op.drop_index(batch_op.f('ix_payment_repairs_created_at'))

    op.drop_table('payment_repairs')
    with op.batch_alter_table('payment_investigations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_payment_investigations_status'))
        batch_op.drop_index(batch_op.f('ix_payment_investigations_payment_id'))
        batch_op.drop_index(batch_op.f('ix_payment_investigations_opened_at'))
        batch_op.drop_index(batch_op.f('ix_payment_investigations_execution_id'))
        batch_op.drop_index(batch_op.f('ix_payment_investigations_created_at'))
        batch_op.drop_index(batch_op.f('ix_payment_investigations_category'))
        batch_op.drop_index(batch_op.f('ix_payment_investigations_case_number'))

    op.drop_table('payment_investigations')
    with op.batch_alter_table('payment_instructions', schema=None) as batch_op:
        batch_op.drop_index('ix_payment_status_value')
        batch_op.drop_index(batch_op.f('ix_payment_instructions_value_date'))
        batch_op.drop_index(batch_op.f('ix_payment_instructions_uetr'))
        batch_op.drop_index(batch_op.f('ix_payment_instructions_status'))
        batch_op.drop_index(batch_op.f('ix_payment_instructions_screening_status'))
        batch_op.drop_index(batch_op.f('ix_payment_instructions_payment_reference'))
        batch_op.drop_index(batch_op.f('ix_payment_instructions_direction'))
        batch_op.drop_index(batch_op.f('ix_payment_instructions_customer_id'))
        batch_op.drop_index(batch_op.f('ix_payment_instructions_created_at'))
        batch_op.drop_index('ix_payment_customer')

    op.drop_table('payment_instructions')
    # ### end Alembic commands ###
