"""initial schema

Revision ID: e6e124c8f403
Revises: 
Create Date: 2026-08-04 19:03:53.301409+00:00
"""
from __future__ import annotations

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy import Text
from sqlalchemy.dialects import postgresql

import app.db.base

revision: str = 'e6e124c8f403'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agents',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('availability', sa.String(length=24), nullable=False),
    sa.Column('lifecycle_state', sa.String(length=24), nullable=False),
    sa.Column('owner', sa.String(length=160), nullable=False),
    sa.Column('owner_email', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=120), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('is_builtin', sa.Boolean(), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('tags', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('tools', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('knowledge_sources', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('sla_latency_ms', sa.Integer(), nullable=False),
    sa.Column('monthly_budget_usd', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_agents_availability'), ['availability'], unique=False)
        batch_op.create_index(batch_op.f('ix_agents_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_agents_key'), ['key'], unique=True)
        batch_op.create_index(batch_op.f('ix_agents_lifecycle_state'), ['lifecycle_state'], unique=False)

    op.create_table('aml_alerts',
    sa.Column('alert_number', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=True),
    sa.Column('rule_code', sa.String(length=40), nullable=False),
    sa.Column('rule_name', sa.String(length=200), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('score', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('transaction_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('detected_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aml_alerts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aml_alerts_alert_number'), ['alert_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_aml_alerts_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_aml_alerts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_aml_alerts_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_aml_alerts_detected_at'), ['detected_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_aml_alerts_rule_code'), ['rule_code'], unique=False)
        batch_op.create_index(batch_op.f('ix_aml_alerts_severity'), ['severity'], unique=False)
        batch_op.create_index(batch_op.f('ix_aml_alerts_status'), ['status'], unique=False)

    op.create_table('aml_cases',
    sa.Column('case_number', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('typologies', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('alert_ids', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('timeline', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('evidence', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('narrative', sa.Text(), nullable=True),
    sa.Column('investigator', sa.String(length=255), nullable=True),
    sa.Column('execution_id', sa.String(length=36), nullable=True),
    sa.Column('sar_filed', sa.Boolean(), nullable=False),
    sa.Column('closed_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('disposition', sa.String(length=60), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('aml_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_aml_cases_case_number'), ['case_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_aml_cases_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_aml_cases_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_aml_cases_execution_id'), ['execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_aml_cases_status'), ['status'], unique=False)

    op.create_table('audit_logs',
    sa.Column('actor_id', sa.String(length=36), nullable=True),
    sa.Column('actor_email', sa.String(length=255), nullable=True),
    sa.Column('actor_type', sa.String(length=32), nullable=False),
    sa.Column('action', sa.String(length=120), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False),
    sa.Column('resource_id', sa.String(length=128), nullable=True),
    sa.Column('outcome', sa.String(length=32), nullable=False),
    sa.Column('severity', sa.String(length=16), nullable=False),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.create_index('ix_audit_actor_action', ['actor_id', 'action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_action'), ['action'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_actor_id'), ['actor_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_request_id'), ['request_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_resource_type'), ['resource_type'], unique=False)
        batch_op.create_index(batch_op.f('ix_audit_logs_trace_id'), ['trace_id'], unique=False)
        batch_op.create_index('ix_audit_resource', ['resource_type', 'resource_id'], unique=False)

    op.create_table('cost_records',
    sa.Column('timestamp', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('execution_id', sa.String(length=36), nullable=True),
    sa.Column('span_id', sa.String(length=64), nullable=True),
    sa.Column('agent_key', sa.String(length=80), nullable=True),
    sa.Column('category', sa.String(length=32), nullable=False),
    sa.Column('provider', sa.String(length=60), nullable=False),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('tool', sa.String(length=120), nullable=True),
    sa.Column('tokens_input', sa.Integer(), nullable=False),
    sa.Column('tokens_output', sa.Integer(), nullable=False),
    sa.Column('tokens_cached', sa.Integer(), nullable=False),
    sa.Column('units', sa.Float(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=120), nullable=True),
    sa.Column('latency_ms', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cost_records', schema=None) as batch_op:
        batch_op.create_index('ix_cost_model', ['model'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_records_agent_key'), ['agent_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_records_department'), ['department'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_records_execution_id'), ['execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_records_provider'), ['provider'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_records_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_cost_records_user_id'), ['user_id'], unique=False)
        batch_op.create_index('ix_cost_ts_agent', ['timestamp', 'agent_key'], unique=False)

    op.create_table('customers',
    sa.Column('customer_number', sa.String(length=32), nullable=False),
    sa.Column('full_name', sa.String(length=200), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=True),
    sa.Column('phone', sa.String(length=40), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('nationality', sa.String(length=80), nullable=False),
    sa.Column('address_line1', sa.String(length=255), nullable=True),
    sa.Column('address_city', sa.String(length=120), nullable=True),
    sa.Column('address_state', sa.String(length=120), nullable=True),
    sa.Column('address_postcode', sa.String(length=24), nullable=True),
    sa.Column('address_country', sa.String(length=80), nullable=False),
    sa.Column('segment', sa.String(length=40), nullable=False),
    sa.Column('kyc_status', sa.String(length=32), nullable=False),
    sa.Column('risk_rating', sa.String(length=24), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('pep_flag', sa.Boolean(), nullable=False),
    sa.Column('sanctions_flag', sa.Boolean(), nullable=False),
    sa.Column('onboarded_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('relationship_manager', sa.String(length=160), nullable=True),
    sa.Column('auth_pin_hash', sa.String(length=255), nullable=True),
    sa.Column('security_question', sa.String(length=255), nullable=True),
    sa.Column('security_answer_hash', sa.String(length=255), nullable=True),
    sa.Column('failed_auth_attempts', sa.Integer(), nullable=False),
    sa.Column('attributes', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_customers_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_customer_number'), ['customer_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_customers_email'), ['email'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_full_name'), ['full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_kyc_status'), ['kyc_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_phone'), ['phone'], unique=False)
        batch_op.create_index(batch_op.f('ix_customers_risk_rating'), ['risk_rating'], unique=False)

    op.create_table('evaluations',
    sa.Column('execution_id', sa.String(length=36), nullable=False),
    sa.Column('agent_key', sa.String(length=80), nullable=False),
    sa.Column('evaluator', sa.String(length=60), nullable=False),
    sa.Column('faithfulness', sa.Float(), nullable=True),
    sa.Column('groundedness', sa.Float(), nullable=True),
    sa.Column('hallucination_score', sa.Float(), nullable=True),
    sa.Column('citation_score', sa.Float(), nullable=True),
    sa.Column('tool_success_rate', sa.Float(), nullable=True),
    sa.Column('answer_relevance', sa.Float(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('cost_usd', sa.Float(), nullable=True),
    sa.Column('human_rating', sa.Integer(), nullable=True),
    sa.Column('human_feedback', sa.Text(), nullable=True),
    sa.Column('reviewer_email', sa.String(length=255), nullable=True),
    sa.Column('details', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_evaluations_agent_key'), ['agent_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluations_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_evaluations_execution_id'), ['execution_id'], unique=False)

    op.create_table('executions',
    sa.Column('agent_key', sa.String(length=80), nullable=False),
    sa.Column('agent_version', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('trigger', sa.String(length=32), nullable=False),
    sa.Column('input', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('output', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('final_response', sa.Text(), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('error_type', sa.String(length=80), nullable=True),
    sa.Column('plan', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('reasoning', sa.Text(), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('correlation_id', sa.String(length=64), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('thread_id', sa.String(length=64), nullable=True),
    sa.Column('user_id', sa.String(length=36), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('department', sa.String(length=120), nullable=True),
    sa.Column('model', sa.String(length=120), nullable=True),
    sa.Column('provider', sa.String(length=60), nullable=True),
    sa.Column('tokens_input', sa.Integer(), nullable=False),
    sa.Column('tokens_output', sa.Integer(), nullable=False),
    sa.Column('tokens_embedding', sa.Integer(), nullable=False),
    sa.Column('tokens_cached', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('started_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('finished_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('queue_ms', sa.Integer(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('tool_call_count', sa.Integer(), nullable=False),
    sa.Column('llm_call_count', sa.Integer(), nullable=False),
    sa.Column('approval_count', sa.Integer(), nullable=False),
    sa.Column('node_path', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('checkpoint', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('artifacts', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('executions', schema=None) as batch_op:
        batch_op.create_index('ix_exec_agent_created', ['agent_key', 'created_at'], unique=False)
        batch_op.create_index('ix_exec_status_created', ['status', 'created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_executions_agent_key'), ['agent_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_executions_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_executions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_executions_department'), ['department'], unique=False)
        batch_op.create_index(batch_op.f('ix_executions_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_executions_thread_id'), ['thread_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_executions_trace_id'), ['trace_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_executions_user_id'), ['user_id'], unique=False)

    op.create_table('faq_entries',
    sa.Column('question', sa.String(length=500), nullable=False),
    sa.Column('answer', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=80), nullable=False),
    sa.Column('keywords', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('product', sa.String(length=80), nullable=True),
    sa.Column('hit_count', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('faq_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_faq_entries_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_faq_entries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_faq_entries_question'), ['question'], unique=False)

    op.create_table('feature_flags',
    sa.Column('key', sa.String(length=120), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('rollout_percentage', sa.Integer(), nullable=False),
    sa.Column('targeting', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('updated_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('feature_flags', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_feature_flags_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_feature_flags_key'), ['key'], unique=True)

    op.create_table('knowledge_sources',
    sa.Column('key', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=180), nullable=False),
    sa.Column('connector', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('last_sync_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('document_count', sa.Integer(), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('embedding_model', sa.String(length=120), nullable=True),
    sa.Column('vector_dimensions', sa.Integer(), nullable=False),
    sa.Column('classification', sa.String(length=40), nullable=False),
    sa.Column('sync_interval_minutes', sa.Integer(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('knowledge_sources', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_knowledge_sources_connector'), ['connector'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_sources_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_knowledge_sources_key'), ['key'], unique=True)

    op.create_table('kyc_cases',
    sa.Column('case_number', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('applicant_name', sa.String(length=200), nullable=False),
    sa.Column('applicant_email', sa.String(length=255), nullable=True),
    sa.Column('applicant_phone', sa.String(length=40), nullable=True),
    sa.Column('date_of_birth', sa.Date(), nullable=True),
    sa.Column('nationality', sa.String(length=80), nullable=False),
    sa.Column('declared_address', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('decision', sa.String(length=32), nullable=True),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('risk_band', sa.String(length=16), nullable=False),
    sa.Column('sanctions_hits', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('pep_hits', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('face_match_score', sa.Float(), nullable=True),
    sa.Column('address_verified', sa.Boolean(), nullable=False),
    sa.Column('execution_id', sa.String(length=36), nullable=True),
    sa.Column('report_uri', sa.String(length=1000), nullable=True),
    sa.Column('findings', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('decided_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('decided_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kyc_cases', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kyc_cases_case_number'), ['case_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_kyc_cases_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_kyc_cases_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kyc_cases_execution_id'), ['execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kyc_cases_status'), ['status'], unique=False)

    op.create_table('log_records',
    sa.Column('timestamp', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('level', sa.String(length=16), nullable=False),
    sa.Column('logger', sa.String(length=120), nullable=False),
    sa.Column('message', sa.Text(), nullable=False),
    sa.Column('agent_key', sa.String(length=80), nullable=True),
    sa.Column('execution_id', sa.String(length=36), nullable=True),
    sa.Column('correlation_id', sa.String(length=64), nullable=True),
    sa.Column('trace_id', sa.String(length=64), nullable=True),
    sa.Column('span_id', sa.String(length=64), nullable=True),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('attributes', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('log_records', schema=None) as batch_op:
        batch_op.create_index('ix_log_exec', ['execution_id', 'timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_records_agent_key'), ['agent_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_records_correlation_id'), ['correlation_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_records_execution_id'), ['execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_records_level'), ['level'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_records_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_log_records_trace_id'), ['trace_id'], unique=False)
        batch_op.create_index('ix_log_ts_level', ['timestamp', 'level'], unique=False)

    op.create_table('memory_threads',
    sa.Column('thread_key', sa.String(length=120), nullable=False),
    sa.Column('agent_key', sa.String(length=80), nullable=False),
    sa.Column('subject_id', sa.String(length=120), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('sentiment', sa.String(length=24), nullable=True),
    sa.Column('sentiment_score', sa.Float(), nullable=True),
    sa.Column('facts', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('message_count', sa.Integer(), nullable=False),
    sa.Column('last_activity_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memory_threads', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memory_threads_agent_key'), ['agent_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_threads_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_threads_subject_id'), ['subject_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_threads_thread_key'), ['thread_key'], unique=True)

    op.create_table('playground_runs',
    sa.Column('prompt', sa.Text(), nullable=False),
    sa.Column('system_prompt', sa.Text(), nullable=True),
    sa.Column('models', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('parameters', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('results', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('total_cost_usd', sa.Float(), nullable=False),
    sa.Column('user_email', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('playground_runs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_playground_runs_created_at'), ['created_at'], unique=False)

    op.create_table('portfolios',
    sa.Column('portfolio_code', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('strategy', sa.String(length=80), nullable=False),
    sa.Column('base_currency', sa.String(length=3), nullable=False),
    sa.Column('cash_balance', sa.Float(), nullable=False),
    sa.Column('benchmark', sa.String(length=60), nullable=False),
    sa.Column('risk_profile', sa.String(length=24), nullable=False),
    sa.Column('mandate', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_portfolios_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolios_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_portfolios_portfolio_code'), ['portfolio_code'], unique=True)

    op.create_table('price_bars',
    sa.Column('symbol', sa.String(length=24), nullable=False),
    sa.Column('bar_date', sa.Date(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Float(), nullable=False),
    sa.Column('source', sa.String(length=40), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('price_bars', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_price_bars_bar_date'), ['bar_date'], unique=False)
        batch_op.create_index(batch_op.f('ix_price_bars_symbol'), ['symbol'], unique=False)
        batch_op.create_index('ix_price_symbol_date', ['symbol', 'bar_date'], unique=True)

    op.create_table('research_notes',
    sa.Column('symbol', sa.String(length=24), nullable=True),
    sa.Column('title', sa.String(length=300), nullable=False),
    sa.Column('thesis', sa.Text(), nullable=False),
    sa.Column('recommendation', sa.String(length=24), nullable=True),
    sa.Column('target_price', sa.Float(), nullable=True),
    sa.Column('horizon_months', sa.Integer(), nullable=False),
    sa.Column('conviction', sa.String(length=16), nullable=False),
    sa.Column('risks', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('catalysts', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('citations', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('analyst', sa.String(length=160), nullable=True),
    sa.Column('execution_id', sa.String(length=36), nullable=True),
    sa.Column('artifact_uri', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('research_notes', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_research_notes_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_notes_execution_id'), ['execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_research_notes_symbol'), ['symbol'], unique=False)

    op.create_table('sanctions_entries',
    sa.Column('list_name', sa.String(length=60), nullable=False),
    sa.Column('entry_type', sa.String(length=24), nullable=False),
    sa.Column('full_name', sa.String(length=300), nullable=False),
    sa.Column('normalised_name', sa.String(length=300), nullable=False),
    sa.Column('aliases', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('date_of_birth', sa.String(length=40), nullable=True),
    sa.Column('nationality', sa.String(length=80), nullable=True),
    sa.Column('program', sa.String(length=120), nullable=True),
    sa.Column('position', sa.String(length=200), nullable=True),
    sa.Column('is_pep', sa.Boolean(), nullable=False),
    sa.Column('source_url', sa.String(length=500), nullable=True),
    sa.Column('listed_on', sa.Date(), nullable=True),
    sa.Column('remarks', sa.Text(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sanctions_entries', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sanctions_entries_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sanctions_entries_full_name'), ['full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_sanctions_entries_is_pep'), ['is_pep'], unique=False)
        batch_op.create_index(batch_op.f('ix_sanctions_entries_list_name'), ['list_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_sanctions_entries_normalised_name'), ['normalised_name'], unique=False)
        batch_op.create_index('ix_sanctions_name_norm', ['normalised_name'], unique=False)

    op.create_table('sar_reports',
    sa.Column('sar_number', sa.String(length=32), nullable=False),
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('filing_institution', sa.String(length=200), nullable=False),
    sa.Column('regulator', sa.String(length=80), nullable=False),
    sa.Column('suspicious_amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('activity_start', sa.Date(), nullable=True),
    sa.Column('activity_end', sa.Date(), nullable=True),
    sa.Column('typologies', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('narrative', sa.Text(), nullable=False),
    sa.Column('supporting_transactions', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('artifact_uri', sa.String(length=1000), nullable=True),
    sa.Column('approved_by', sa.String(length=255), nullable=True),
    sa.Column('filed_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('execution_id', sa.String(length=36), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('sar_reports', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_sar_reports_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sar_reports_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_sar_reports_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_sar_reports_sar_number'), ['sar_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_sar_reports_status'), ['status'], unique=False)

    op.create_table('scheduled_jobs',
    sa.Column('agent_key', sa.String(length=80), nullable=False),
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('cron', sa.String(length=120), nullable=False),
    sa.Column('timezone', sa.String(length=64), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('enabled', sa.Boolean(), nullable=False),
    sa.Column('last_run_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('next_run_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('scheduled_jobs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_scheduled_jobs_agent_key'), ['agent_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_scheduled_jobs_created_at'), ['created_at'], unique=False)

    op.create_table('search_query_logs',
    sa.Column('timestamp', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('query', sa.Text(), nullable=False),
    sa.Column('agent_key', sa.String(length=80), nullable=True),
    sa.Column('execution_id', sa.String(length=36), nullable=True),
    sa.Column('collection', sa.String(length=120), nullable=False),
    sa.Column('backend', sa.String(length=32), nullable=False),
    sa.Column('top_k', sa.Integer(), nullable=False),
    sa.Column('result_count', sa.Integer(), nullable=False),
    sa.Column('latency_ms', sa.Float(), nullable=False),
    sa.Column('top_score', sa.Float(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('search_query_logs', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_search_query_logs_execution_id'), ['execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_search_query_logs_timestamp'), ['timestamp'], unique=False)

    op.create_table('securities',
    sa.Column('symbol', sa.String(length=24), nullable=False),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('exchange', sa.String(length=24), nullable=False),
    sa.Column('asset_class', sa.String(length=32), nullable=False),
    sa.Column('sector', sa.String(length=80), nullable=True),
    sa.Column('industry', sa.String(length=120), nullable=True),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('country', sa.String(length=3), nullable=False),
    sa.Column('cik', sa.String(length=16), nullable=True),
    sa.Column('isin', sa.String(length=16), nullable=True),
    sa.Column('last_price', sa.Float(), nullable=True),
    sa.Column('last_price_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('fundamentals', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('securities', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_securities_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_securities_sector'), ['sector'], unique=False)
        batch_op.create_index(batch_op.f('ix_securities_symbol'), ['symbol'], unique=True)

    op.create_table('stored_secrets',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('category', sa.String(length=64), nullable=False),
    sa.Column('sealed_value', sa.Text(), nullable=False),
    sa.Column('hint', sa.String(length=64), nullable=False),
    sa.Column('backend', sa.String(length=32), nullable=False),
    sa.Column('rotated_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('rotation_interval_days', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('stored_secrets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_stored_secrets_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_stored_secrets_name'), ['name'], unique=True)

    op.create_table('tickets',
    sa.Column('ticket_number', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=True),
    sa.Column('subject', sa.String(length=300), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('priority', sa.String(length=16), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('sentiment', sa.String(length=24), nullable=True),
    sa.Column('assigned_team', sa.String(length=120), nullable=True),
    sa.Column('escalated', sa.Boolean(), nullable=False),
    sa.Column('escalation_reason', sa.Text(), nullable=True),
    sa.Column('execution_id', sa.String(length=36), nullable=True),
    sa.Column('resolved_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('sla_due_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('notes', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tickets_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tickets_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tickets_execution_id'), ['execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_tickets_priority'), ['priority'], unique=False)
        batch_op.create_index(batch_op.f('ix_tickets_status'), ['status'], unique=False)
        batch_op.create_index(batch_op.f('ix_tickets_ticket_number'), ['ticket_number'], unique=True)

    op.create_table('tool_health',
    sa.Column('tool_name', sa.String(length=120), nullable=False),
    sa.Column('category', sa.String(length=60), nullable=False),
    sa.Column('total_calls', sa.Integer(), nullable=False),
    sa.Column('total_failures', sa.Integer(), nullable=False),
    sa.Column('total_timeouts', sa.Integer(), nullable=False),
    sa.Column('total_retries', sa.Integer(), nullable=False),
    sa.Column('p50_latency_ms', sa.Float(), nullable=False),
    sa.Column('p95_latency_ms', sa.Float(), nullable=False),
    sa.Column('last_latency_ms', sa.Float(), nullable=False),
    sa.Column('last_status', sa.String(length=24), nullable=False),
    sa.Column('last_error', sa.Text(), nullable=True),
    sa.Column('last_called_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('latency_samples', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('tool_health', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_tool_health_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_tool_health_tool_name'), ['tool_name'], unique=True)

    op.create_table('users',
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('hashed_password', sa.String(length=255), nullable=True),
    sa.Column('roles', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('department', sa.String(length=120), nullable=False),
    sa.Column('cost_center', sa.String(length=120), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('is_service_account', sa.Boolean(), nullable=False),
    sa.Column('sso_subject', sa.String(length=255), nullable=True),
    sa.Column('sso_provider', sa.String(length=64), nullable=True),
    sa.Column('mfa_secret', sa.String(length=255), nullable=True),
    sa.Column('mfa_enabled', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('failed_login_count', sa.Integer(), nullable=False),
    sa.Column('locked_until', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('preferences', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_users_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_users_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_users_sso_subject'), ['sso_subject'], unique=False)

    op.create_table('accounts',
    sa.Column('account_number', sa.String(length=34), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('account_type', sa.String(length=40), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('balance', sa.Float(), nullable=False),
    sa.Column('available_balance', sa.Float(), nullable=False),
    sa.Column('hold_amount', sa.Float(), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('branch_code', sa.String(length=24), nullable=True),
    sa.Column('ifsc', sa.String(length=24), nullable=True),
    sa.Column('opened_on', sa.Date(), nullable=True),
    sa.Column('overdraft_limit', sa.Float(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_accounts_account_number'), ['account_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_accounts_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_accounts_status'), ['status'], unique=False)

    op.create_table('agent_versions',
    sa.Column('agent_id', sa.String(length=36), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('config', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('changelog', sa.Text(), nullable=False),
    sa.Column('published', sa.Boolean(), nullable=False),
    sa.Column('published_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('published_by', sa.String(length=255), nullable=True),
    sa.Column('is_current', sa.Boolean(), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['agent_id'], ['agents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('agent_versions', schema=None) as batch_op:
        batch_op.create_index('ix_agent_version_unique', ['agent_id', 'version'], unique=True)
        batch_op.create_index(batch_op.f('ix_agent_versions_agent_id'), ['agent_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_versions_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_agent_versions_is_current'), ['is_current'], unique=False)

    op.create_table('api_keys',
    sa.Column('name', sa.String(length=160), nullable=False),
    sa.Column('prefix', sa.String(length=16), nullable=False),
    sa.Column('hashed_key', sa.String(length=128), nullable=False),
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('scopes', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('rate_limit_per_minute', sa.Integer(), nullable=False),
    sa.Column('expires_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('last_used_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('usage_count', sa.Integer(), nullable=False),
    sa.Column('revoked_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_api_keys_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_hashed_key'), ['hashed_key'], unique=True)
        batch_op.create_index(batch_op.f('ix_api_keys_prefix'), ['prefix'], unique=False)
        batch_op.create_index(batch_op.f('ix_api_keys_user_id'), ['user_id'], unique=False)

    op.create_table('approvals',
    sa.Column('execution_id', sa.String(length=36), nullable=False),
    sa.Column('agent_key', sa.String(length=80), nullable=False),
    sa.Column('node', sa.String(length=60), nullable=False),
    sa.Column('title', sa.String(length=240), nullable=False),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('risk_level', sa.String(length=16), nullable=False),
    sa.Column('required_role', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('requested_by', sa.String(length=255), nullable=True),
    sa.Column('reviewer_id', sa.String(length=36), nullable=True),
    sa.Column('reviewer_email', sa.String(length=255), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('decided_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('expires_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('timeline', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_approvals_agent_key'), ['agent_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_execution_id'), ['execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_approvals_status'), ['status'], unique=False)

    op.create_table('cards',
    sa.Column('card_number_masked', sa.String(length=24), nullable=False),
    sa.Column('card_token', sa.String(length=64), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=True),
    sa.Column('card_type', sa.String(length=24), nullable=False),
    sa.Column('network', sa.String(length=24), nullable=False),
    sa.Column('product_name', sa.String(length=120), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('credit_limit', sa.Float(), nullable=False),
    sa.Column('available_credit', sa.Float(), nullable=False),
    sa.Column('current_balance', sa.Float(), nullable=False),
    sa.Column('minimum_due', sa.Float(), nullable=False),
    sa.Column('statement_date', sa.Date(), nullable=True),
    sa.Column('due_date', sa.Date(), nullable=True),
    sa.Column('apr', sa.Float(), nullable=False),
    sa.Column('reward_points', sa.Integer(), nullable=False),
    sa.Column('expiry', sa.String(length=7), nullable=True),
    sa.Column('issued_on', sa.Date(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_cards_card_number_masked'), ['card_number_masked'], unique=False)
        batch_op.create_index(batch_op.f('ix_cards_card_token'), ['card_token'], unique=True)
        batch_op.create_index(batch_op.f('ix_cards_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_cards_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_cards_status'), ['status'], unique=False)

    op.create_table('documents',
    sa.Column('source_id', sa.String(length=36), nullable=False),
    sa.Column('external_id', sa.String(length=255), nullable=True),
    sa.Column('title', sa.String(length=500), nullable=False),
    sa.Column('uri', sa.String(length=1000), nullable=True),
    sa.Column('mime_type', sa.String(length=120), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('content_hash', sa.String(length=64), nullable=False),
    sa.Column('author', sa.String(length=255), nullable=True),
    sa.Column('classification', sa.String(length=40), nullable=False),
    sa.Column('doc_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('embedding_status', sa.String(length=24), nullable=False),
    sa.Column('chunk_count', sa.Integer(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('version', sa.Integer(), nullable=False),
    sa.Column('artifact_uri', sa.String(length=1000), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['source_id'], ['knowledge_sources.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.create_index('ix_doc_source_ext', ['source_id', 'external_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_content_hash'), ['content_hash'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_embedding_status'), ['embedding_status'], unique=False)
        batch_op.create_index(batch_op.f('ix_documents_source_id'), ['source_id'], unique=False)

    op.create_table('execution_events',
    sa.Column('execution_id', sa.String(length=36), nullable=False),
    sa.Column('sequence', sa.Integer(), nullable=False),
    sa.Column('type', sa.String(length=60), nullable=False),
    sa.Column('node', sa.String(length=60), nullable=True),
    sa.Column('span_id', sa.String(length=64), nullable=True),
    sa.Column('payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('timestamp', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('execution_events', schema=None) as batch_op:
        batch_op.create_index('ix_event_exec_seq', ['execution_id', 'sequence'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_events_execution_id'), ['execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_events_timestamp'), ['timestamp'], unique=False)
        batch_op.create_index(batch_op.f('ix_execution_events_type'), ['type'], unique=False)

    op.create_table('holdings',
    sa.Column('portfolio_id', sa.String(length=36), nullable=False),
    sa.Column('symbol', sa.String(length=24), nullable=False),
    sa.Column('quantity', sa.Float(), nullable=False),
    sa.Column('average_cost', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('asset_class', sa.String(length=32), nullable=False),
    sa.Column('sector', sa.String(length=80), nullable=True),
    sa.Column('opened_on', sa.Date(), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['portfolio_id'], ['portfolios.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_holdings_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_holdings_portfolio_id'), ['portfolio_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_holdings_symbol'), ['symbol'], unique=False)

    op.create_table('kyc_documents',
    sa.Column('case_id', sa.String(length=36), nullable=False),
    sa.Column('doc_type', sa.String(length=40), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('mime_type', sa.String(length=80), nullable=False),
    sa.Column('artifact_uri', sa.String(length=1000), nullable=True),
    sa.Column('sha256', sa.String(length=64), nullable=True),
    sa.Column('ocr_engine', sa.String(length=60), nullable=True),
    sa.Column('ocr_text', sa.Text(), nullable=True),
    sa.Column('extracted_fields', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('classification_confidence', sa.Float(), nullable=True),
    sa.Column('verification_status', sa.String(length=32), nullable=False),
    sa.Column('verification_notes', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['case_id'], ['kyc_cases.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('kyc_documents', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_kyc_documents_case_id'), ['case_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_kyc_documents_created_at'), ['created_at'], unique=False)

    op.create_table('loans',
    sa.Column('loan_number', sa.String(length=32), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('loan_type', sa.String(length=40), nullable=False),
    sa.Column('principal', sa.Float(), nullable=False),
    sa.Column('outstanding', sa.Float(), nullable=False),
    sa.Column('interest_rate', sa.Float(), nullable=False),
    sa.Column('tenure_months', sa.Integer(), nullable=False),
    sa.Column('emi_amount', sa.Float(), nullable=False),
    sa.Column('emis_paid', sa.Integer(), nullable=False),
    sa.Column('next_due_date', sa.Date(), nullable=True),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('days_past_due', sa.Integer(), nullable=False),
    sa.Column('disbursed_on', sa.Date(), nullable=True),
    sa.Column('collateral', sa.String(length=255), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['customer_id'], ['customers.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_loans_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_loans_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_loans_loan_number'), ['loan_number'], unique=True)
        batch_op.create_index(batch_op.f('ix_loans_status'), ['status'], unique=False)

    op.create_table('memory_messages',
    sa.Column('thread_id', sa.String(length=36), nullable=False),
    sa.Column('role', sa.String(length=24), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('execution_id', sa.String(length=36), nullable=True),
    sa.Column('tokens', sa.Integer(), nullable=False),
    sa.Column('msg_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['memory_threads.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('memory_messages', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_memory_messages_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_memory_messages_thread_id'), ['thread_id'], unique=False)

    op.create_table('refresh_tokens',
    sa.Column('user_id', sa.String(length=36), nullable=False),
    sa.Column('jti', sa.String(length=64), nullable=False),
    sa.Column('expires_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('revoked_at', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('user_agent', sa.String(length=255), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_refresh_tokens_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_jti'), ['jti'], unique=True)
        batch_op.create_index(batch_op.f('ix_refresh_tokens_user_id'), ['user_id'], unique=False)

    op.create_table('spans',
    sa.Column('execution_id', sa.String(length=36), nullable=False),
    sa.Column('trace_id', sa.String(length=64), nullable=False),
    sa.Column('span_id', sa.String(length=64), nullable=False),
    sa.Column('parent_span_id', sa.String(length=64), nullable=True),
    sa.Column('name', sa.String(length=200), nullable=False),
    sa.Column('kind', sa.String(length=40), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('start_time', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('end_time', app.db.base.UTCDateTime(timezone=True), nullable=True),
    sa.Column('duration_ms', sa.Float(), nullable=True),
    sa.Column('attributes', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('events', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('input_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('output_payload', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=True),
    sa.Column('error', sa.Text(), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=False),
    sa.Column('tokens_input', sa.Integer(), nullable=False),
    sa.Column('tokens_output', sa.Integer(), nullable=False),
    sa.Column('cost_usd', sa.Float(), nullable=False),
    sa.Column('request_id', sa.String(length=64), nullable=True),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['executions.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('spans', schema=None) as batch_op:
        batch_op.create_index('ix_span_exec_start', ['execution_id', 'start_time'], unique=False)
        batch_op.create_index(batch_op.f('ix_spans_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_spans_execution_id'), ['execution_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_spans_kind'), ['kind'], unique=False)
        batch_op.create_index(batch_op.f('ix_spans_parent_span_id'), ['parent_span_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_spans_span_id'), ['span_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_spans_trace_id'), ['trace_id'], unique=False)

    op.create_table('chunks',
    sa.Column('document_id', sa.String(length=36), nullable=False),
    sa.Column('source_key', sa.String(length=80), nullable=False),
    sa.Column('chunk_index', sa.Integer(), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('token_count', sa.Integer(), nullable=False),
    sa.Column('heading', sa.String(length=500), nullable=True),
    sa.Column('embedding', sa.LargeBinary(), nullable=True),
    sa.Column('embedding_model', sa.String(length=120), nullable=True),
    sa.Column('dimensions', sa.Integer(), nullable=False),
    sa.Column('vector_id', sa.String(length=64), nullable=True),
    sa.Column('chunk_metadata', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.Column('created_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', app.db.base.UTCDateTime(timezone=True), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['document_id'], ['documents.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('chunks', schema=None) as batch_op:
        batch_op.create_index('ix_chunk_doc_index', ['document_id', 'chunk_index'], unique=False)
        batch_op.create_index(batch_op.f('ix_chunks_created_at'), ['created_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_chunks_document_id'), ['document_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_chunks_source_key'), ['source_key'], unique=False)
        batch_op.create_index(batch_op.f('ix_chunks_vector_id'), ['vector_id'], unique=False)

    op.create_table('transactions',
    sa.Column('reference', sa.String(length=48), nullable=False),
    sa.Column('account_id', sa.String(length=36), nullable=False),
    sa.Column('customer_id', sa.String(length=36), nullable=False),
    sa.Column('booked_at', app.db.base.UTCDateTime(timezone=True), nullable=False),
    sa.Column('amount', sa.Float(), nullable=False),
    sa.Column('currency', sa.String(length=3), nullable=False),
    sa.Column('direction', sa.String(length=8), nullable=False),
    sa.Column('channel', sa.String(length=32), nullable=False),
    sa.Column('merchant', sa.String(length=200), nullable=True),
    sa.Column('category', sa.String(length=80), nullable=True),
    sa.Column('description', sa.String(length=400), nullable=False),
    sa.Column('counterparty_name', sa.String(length=200), nullable=True),
    sa.Column('counterparty_account', sa.String(length=48), nullable=True),
    sa.Column('counterparty_bank', sa.String(length=120), nullable=True),
    sa.Column('country', sa.String(length=3), nullable=False),
    sa.Column('status', sa.String(length=24), nullable=False),
    sa.Column('balance_after', sa.Float(), nullable=True),
    sa.Column('is_flagged', sa.Boolean(), nullable=False),
    sa.Column('risk_score', sa.Float(), nullable=False),
    sa.Column('device_id', sa.String(length=80), nullable=True),
    sa.Column('ip_address', sa.String(length=64), nullable=True),
    sa.Column('attributes', sa.JSON().with_variant(postgresql.JSONB(astext_type=Text()), 'postgresql'), nullable=False),
    sa.Column('id', sa.String(length=36), nullable=False),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_transactions_account_id'), ['account_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_booked_at'), ['booked_at'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_category'), ['category'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_customer_id'), ['customer_id'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_is_flagged'), ['is_flagged'], unique=False)
        batch_op.create_index(batch_op.f('ix_transactions_reference'), ['reference'], unique=True)
        batch_op.create_index('ix_txn_account_time', ['account_id', 'booked_at'], unique=False)
        batch_op.create_index('ix_txn_flags', ['is_flagged', 'booked_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('transactions', schema=None) as batch_op:
        batch_op.drop_index('ix_txn_flags')
        batch_op.drop_index('ix_txn_account_time')
        batch_op.drop_index(batch_op.f('ix_transactions_reference'))
        batch_op.drop_index(batch_op.f('ix_transactions_is_flagged'))
        batch_op.drop_index(batch_op.f('ix_transactions_customer_id'))
        batch_op.drop_index(batch_op.f('ix_transactions_category'))
        batch_op.drop_index(batch_op.f('ix_transactions_booked_at'))
        batch_op.drop_index(batch_op.f('ix_transactions_account_id'))

    op.drop_table('transactions')
    with op.batch_alter_table('chunks', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_chunks_vector_id'))
        batch_op.drop_index(batch_op.f('ix_chunks_source_key'))
        batch_op.drop_index(batch_op.f('ix_chunks_document_id'))
        batch_op.drop_index(batch_op.f('ix_chunks_created_at'))
        batch_op.drop_index('ix_chunk_doc_index')

    op.drop_table('chunks')
    with op.batch_alter_table('spans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_spans_trace_id'))
        batch_op.drop_index(batch_op.f('ix_spans_span_id'))
        batch_op.drop_index(batch_op.f('ix_spans_parent_span_id'))
        batch_op.drop_index(batch_op.f('ix_spans_kind'))
        batch_op.drop_index(batch_op.f('ix_spans_execution_id'))
        batch_op.drop_index(batch_op.f('ix_spans_created_at'))
        batch_op.drop_index('ix_span_exec_start')

    op.drop_table('spans')
    with op.batch_alter_table('refresh_tokens', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_user_id'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_jti'))
        batch_op.drop_index(batch_op.f('ix_refresh_tokens_created_at'))

    op.drop_table('refresh_tokens')
    with op.batch_alter_table('memory_messages', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memory_messages_thread_id'))
        batch_op.drop_index(batch_op.f('ix_memory_messages_created_at'))

    op.drop_table('memory_messages')
    with op.batch_alter_table('loans', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_loans_status'))
        batch_op.drop_index(batch_op.f('ix_loans_loan_number'))
        batch_op.drop_index(batch_op.f('ix_loans_customer_id'))
        batch_op.drop_index(batch_op.f('ix_loans_created_at'))

    op.drop_table('loans')
    with op.batch_alter_table('kyc_documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kyc_documents_created_at'))
        batch_op.drop_index(batch_op.f('ix_kyc_documents_case_id'))

    op.drop_table('kyc_documents')
    with op.batch_alter_table('holdings', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_holdings_symbol'))
        batch_op.drop_index(batch_op.f('ix_holdings_portfolio_id'))
        batch_op.drop_index(batch_op.f('ix_holdings_created_at'))

    op.drop_table('holdings')
    with op.batch_alter_table('execution_events', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_execution_events_type'))
        batch_op.drop_index(batch_op.f('ix_execution_events_timestamp'))
        batch_op.drop_index(batch_op.f('ix_execution_events_execution_id'))
        batch_op.drop_index('ix_event_exec_seq')

    op.drop_table('execution_events')
    with op.batch_alter_table('documents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_documents_source_id'))
        batch_op.drop_index(batch_op.f('ix_documents_embedding_status'))
        batch_op.drop_index(batch_op.f('ix_documents_created_at'))
        batch_op.drop_index(batch_op.f('ix_documents_content_hash'))
        batch_op.drop_index('ix_doc_source_ext')

    op.drop_table('documents')
    with op.batch_alter_table('cards', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_cards_status'))
        batch_op.drop_index(batch_op.f('ix_cards_customer_id'))
        batch_op.drop_index(batch_op.f('ix_cards_created_at'))
        batch_op.drop_index(batch_op.f('ix_cards_card_token'))
        batch_op.drop_index(batch_op.f('ix_cards_card_number_masked'))

    op.drop_table('cards')
    with op.batch_alter_table('approvals', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_approvals_status'))
        batch_op.drop_index(batch_op.f('ix_approvals_execution_id'))
        batch_op.drop_index(batch_op.f('ix_approvals_created_at'))
        batch_op.drop_index(batch_op.f('ix_approvals_agent_key'))

    op.drop_table('approvals')
    with op.batch_alter_table('api_keys', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_api_keys_user_id'))
        batch_op.drop_index(batch_op.f('ix_api_keys_prefix'))
        batch_op.drop_index(batch_op.f('ix_api_keys_hashed_key'))
        batch_op.drop_index(batch_op.f('ix_api_keys_created_at'))

    op.drop_table('api_keys')
    with op.batch_alter_table('agent_versions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agent_versions_is_current'))
        batch_op.drop_index(batch_op.f('ix_agent_versions_created_at'))
        batch_op.drop_index(batch_op.f('ix_agent_versions_agent_id'))
        batch_op.drop_index('ix_agent_version_unique')

    op.drop_table('agent_versions')
    with op.batch_alter_table('accounts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_accounts_status'))
        batch_op.drop_index(batch_op.f('ix_accounts_customer_id'))
        batch_op.drop_index(batch_op.f('ix_accounts_created_at'))
        batch_op.drop_index(batch_op.f('ix_accounts_account_number'))

    op.drop_table('accounts')
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_users_sso_subject'))
        batch_op.drop_index(batch_op.f('ix_users_email'))
        batch_op.drop_index(batch_op.f('ix_users_created_at'))

    op.drop_table('users')
    with op.batch_alter_table('tool_health', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tool_health_tool_name'))
        batch_op.drop_index(batch_op.f('ix_tool_health_created_at'))

    op.drop_table('tool_health')
    with op.batch_alter_table('tickets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_tickets_ticket_number'))
        batch_op.drop_index(batch_op.f('ix_tickets_status'))
        batch_op.drop_index(batch_op.f('ix_tickets_priority'))
        batch_op.drop_index(batch_op.f('ix_tickets_execution_id'))
        batch_op.drop_index(batch_op.f('ix_tickets_customer_id'))
        batch_op.drop_index(batch_op.f('ix_tickets_created_at'))

    op.drop_table('tickets')
    with op.batch_alter_table('stored_secrets', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_stored_secrets_name'))
        batch_op.drop_index(batch_op.f('ix_stored_secrets_created_at'))

    op.drop_table('stored_secrets')
    with op.batch_alter_table('securities', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_securities_symbol'))
        batch_op.drop_index(batch_op.f('ix_securities_sector'))
        batch_op.drop_index(batch_op.f('ix_securities_created_at'))

    op.drop_table('securities')
    with op.batch_alter_table('search_query_logs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_search_query_logs_timestamp'))
        batch_op.drop_index(batch_op.f('ix_search_query_logs_execution_id'))

    op.drop_table('search_query_logs')
    with op.batch_alter_table('scheduled_jobs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_scheduled_jobs_created_at'))
        batch_op.drop_index(batch_op.f('ix_scheduled_jobs_agent_key'))

    op.drop_table('scheduled_jobs')
    with op.batch_alter_table('sar_reports', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_sar_reports_status'))
        batch_op.drop_index(batch_op.f('ix_sar_reports_sar_number'))
        batch_op.drop_index(batch_op.f('ix_sar_reports_customer_id'))
        batch_op.drop_index(batch_op.f('ix_sar_reports_created_at'))
        batch_op.drop_index(batch_op.f('ix_sar_reports_case_id'))

    op.drop_table('sar_reports')
    with op.batch_alter_table('sanctions_entries', schema=None) as batch_op:
        batch_op.drop_index('ix_sanctions_name_norm')
        batch_op.drop_index(batch_op.f('ix_sanctions_entries_normalised_name'))
        batch_op.drop_index(batch_op.f('ix_sanctions_entries_list_name'))
        batch_op.drop_index(batch_op.f('ix_sanctions_entries_is_pep'))
        batch_op.drop_index(batch_op.f('ix_sanctions_entries_full_name'))
        batch_op.drop_index(batch_op.f('ix_sanctions_entries_created_at'))

    op.drop_table('sanctions_entries')
    with op.batch_alter_table('research_notes', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_research_notes_symbol'))
        batch_op.drop_index(batch_op.f('ix_research_notes_execution_id'))
        batch_op.drop_index(batch_op.f('ix_research_notes_created_at'))

    op.drop_table('research_notes')
    with op.batch_alter_table('price_bars', schema=None) as batch_op:
        batch_op.drop_index('ix_price_symbol_date')
        batch_op.drop_index(batch_op.f('ix_price_bars_symbol'))
        batch_op.drop_index(batch_op.f('ix_price_bars_bar_date'))

    op.drop_table('price_bars')
    with op.batch_alter_table('portfolios', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_portfolios_portfolio_code'))
        batch_op.drop_index(batch_op.f('ix_portfolios_customer_id'))
        batch_op.drop_index(batch_op.f('ix_portfolios_created_at'))

    op.drop_table('portfolios')
    with op.batch_alter_table('playground_runs', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_playground_runs_created_at'))

    op.drop_table('playground_runs')
    with op.batch_alter_table('memory_threads', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_memory_threads_thread_key'))
        batch_op.drop_index(batch_op.f('ix_memory_threads_subject_id'))
        batch_op.drop_index(batch_op.f('ix_memory_threads_created_at'))
        batch_op.drop_index(batch_op.f('ix_memory_threads_agent_key'))

    op.drop_table('memory_threads')
    with op.batch_alter_table('log_records', schema=None) as batch_op:
        batch_op.drop_index('ix_log_ts_level')
        batch_op.drop_index(batch_op.f('ix_log_records_trace_id'))
        batch_op.drop_index(batch_op.f('ix_log_records_timestamp'))
        batch_op.drop_index(batch_op.f('ix_log_records_level'))
        batch_op.drop_index(batch_op.f('ix_log_records_execution_id'))
        batch_op.drop_index(batch_op.f('ix_log_records_correlation_id'))
        batch_op.drop_index(batch_op.f('ix_log_records_agent_key'))
        batch_op.drop_index('ix_log_exec')

    op.drop_table('log_records')
    with op.batch_alter_table('kyc_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_kyc_cases_status'))
        batch_op.drop_index(batch_op.f('ix_kyc_cases_execution_id'))
        batch_op.drop_index(batch_op.f('ix_kyc_cases_customer_id'))
        batch_op.drop_index(batch_op.f('ix_kyc_cases_created_at'))
        batch_op.drop_index(batch_op.f('ix_kyc_cases_case_number'))

    op.drop_table('kyc_cases')
    with op.batch_alter_table('knowledge_sources', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_knowledge_sources_key'))
        batch_op.drop_index(batch_op.f('ix_knowledge_sources_created_at'))
        batch_op.drop_index(batch_op.f('ix_knowledge_sources_connector'))

    op.drop_table('knowledge_sources')
    with op.batch_alter_table('feature_flags', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_feature_flags_key'))
        batch_op.drop_index(batch_op.f('ix_feature_flags_created_at'))

    op.drop_table('feature_flags')
    with op.batch_alter_table('faq_entries', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_faq_entries_question'))
        batch_op.drop_index(batch_op.f('ix_faq_entries_created_at'))
        batch_op.drop_index(batch_op.f('ix_faq_entries_category'))

    op.drop_table('faq_entries')
    with op.batch_alter_table('executions', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_executions_user_id'))
        batch_op.drop_index(batch_op.f('ix_executions_trace_id'))
        batch_op.drop_index(batch_op.f('ix_executions_thread_id'))
        batch_op.drop_index(batch_op.f('ix_executions_status'))
        batch_op.drop_index(batch_op.f('ix_executions_department'))
        batch_op.drop_index(batch_op.f('ix_executions_created_at'))
        batch_op.drop_index(batch_op.f('ix_executions_correlation_id'))
        batch_op.drop_index(batch_op.f('ix_executions_agent_key'))
        batch_op.drop_index('ix_exec_status_created')
        batch_op.drop_index('ix_exec_agent_created')

    op.drop_table('executions')
    with op.batch_alter_table('evaluations', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_evaluations_execution_id'))
        batch_op.drop_index(batch_op.f('ix_evaluations_created_at'))
        batch_op.drop_index(batch_op.f('ix_evaluations_agent_key'))

    op.drop_table('evaluations')
    with op.batch_alter_table('customers', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_customers_risk_rating'))
        batch_op.drop_index(batch_op.f('ix_customers_phone'))
        batch_op.drop_index(batch_op.f('ix_customers_kyc_status'))
        batch_op.drop_index(batch_op.f('ix_customers_full_name'))
        batch_op.drop_index(batch_op.f('ix_customers_email'))
        batch_op.drop_index(batch_op.f('ix_customers_customer_number'))
        batch_op.drop_index(batch_op.f('ix_customers_created_at'))

    op.drop_table('customers')
    with op.batch_alter_table('cost_records', schema=None) as batch_op:
        batch_op.drop_index('ix_cost_ts_agent')
        batch_op.drop_index(batch_op.f('ix_cost_records_user_id'))
        batch_op.drop_index(batch_op.f('ix_cost_records_timestamp'))
        batch_op.drop_index(batch_op.f('ix_cost_records_provider'))
        batch_op.drop_index(batch_op.f('ix_cost_records_execution_id'))
        batch_op.drop_index(batch_op.f('ix_cost_records_department'))
        batch_op.drop_index(batch_op.f('ix_cost_records_agent_key'))
        batch_op.drop_index('ix_cost_model')

    op.drop_table('cost_records')
    with op.batch_alter_table('audit_logs', schema=None) as batch_op:
        batch_op.drop_index('ix_audit_resource')
        batch_op.drop_index(batch_op.f('ix_audit_logs_trace_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_resource_type'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_request_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_created_at'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_actor_id'))
        batch_op.drop_index(batch_op.f('ix_audit_logs_action'))
        batch_op.drop_index('ix_audit_actor_action')

    op.drop_table('audit_logs')
    with op.batch_alter_table('aml_cases', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aml_cases_status'))
        batch_op.drop_index(batch_op.f('ix_aml_cases_execution_id'))
        batch_op.drop_index(batch_op.f('ix_aml_cases_customer_id'))
        batch_op.drop_index(batch_op.f('ix_aml_cases_created_at'))
        batch_op.drop_index(batch_op.f('ix_aml_cases_case_number'))

    op.drop_table('aml_cases')
    with op.batch_alter_table('aml_alerts', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_aml_alerts_status'))
        batch_op.drop_index(batch_op.f('ix_aml_alerts_severity'))
        batch_op.drop_index(batch_op.f('ix_aml_alerts_rule_code'))
        batch_op.drop_index(batch_op.f('ix_aml_alerts_detected_at'))
        batch_op.drop_index(batch_op.f('ix_aml_alerts_customer_id'))
        batch_op.drop_index(batch_op.f('ix_aml_alerts_created_at'))
        batch_op.drop_index(batch_op.f('ix_aml_alerts_case_id'))
        batch_op.drop_index(batch_op.f('ix_aml_alerts_alert_number'))

    op.drop_table('aml_alerts')
    with op.batch_alter_table('agents', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_agents_lifecycle_state'))
        batch_op.drop_index(batch_op.f('ix_agents_key'))
        batch_op.drop_index(batch_op.f('ix_agents_created_at'))
        batch_op.drop_index(batch_op.f('ix_agents_availability'))

    op.drop_table('agents')
    # ### end Alembic commands ###
